.TH plot_I18_files_1.Rmd 1 "2024-06-02" "1.0" "plot_I18_files_1.Rmd Manual"
.SH NAME
plot_I18_files_1.Rmd \- Generats "OUTPUT/calving_2022123.rds" which is needed by "plot_I18_files3.Rmd". It does so from files in turn set up by extractor3.py in DATA/
.SH SYNOPSIS
.B plot_I18_files_1.Rmd

.SH DESCRIPTION

.SH OPTIONS

.SH EXAMPLES

.SH AUTHOR
Peter Thejll
.SH SEE ALSO
~/WORKSHOP/QAANAAQ/DATA