.TH plot_I18_files_3.Rmd 1 "2024-06-02" "1.0" "plot_I18_files_3.Rmd Manual"
.SH NAME
plot_I18_files_3.Rmd \- Helps plot infrasound recordings taken by a CTBTO array of sensors.
.SH SYNOPSIS
.B plot_I18_files_3.Rmd
Uses data prepared by running "plot_I18_files_1.Rmd". plot_I18_files_1.Rmd reads data downloaded from geotool as supplied by VDEC. "plot_I18_files_3.Rmd" generates plots as well as estimates of the time lags between windowed sub-sequences of the data from each of 8 sensors. The data are high-pass filtered using settings inside the code.
.SH DESCRIPTION
Run from Rstudio, or the command line.
.SH OPTIONS
Options are set inside the code.
.SH EXAMPLES
From command line: ../RunChunck plot_I18_files_3.Rmd
.SH AUTHOR
Peter Thejll, with Nis Jepsen
.SH SEE ALSO
~/WORKSHOP/QAANAAQ/
