---
title: "Detect jumps in lon or lat or speed and tabulate - using EMCluster"
output: 
  pdf_document: 
    fig_height: 8
---



```{r}
rm(list=ls())
setwd("~/WORKSHOP/QAANAAQ/")
library(lubridate)
library(geosphere) 
library(dplyr)
library(MASS)
library(mclust)
library(EMCluster)
files <- list.files(path='OUTPUT',pattern='isolated',full.names = TRUE)
idx <- grep('dateRange',files)
files <- files[-idx]
#
Groups_wanted <- 7
```

# define calculate speeds function
```{r}
speed_calc <- function(df_her) {
  # Initialize the speed vector
  speed <- numeric(nrow(df_her) - 1)
  
  # Calculate the time differences
  time_diff <- as.numeric(difftime(df_her$DateTimeUTC[-1], df_her$DateTimeUTC[-nrow(df_her)], units = "secs"))
  
  # Loop through each time point
  for (itime in 1:(nrow(df_her) - 1)) {
    distance <- distHaversine(cbind(df_her$Longitude[itime], df_her$Latitude[itime]),
                              cbind(df_her$Longitude[itime + 1], df_her$Latitude[itime + 1]),
                              r = 6378137)
    speed[itime] <- (distance / time_diff[itime]) # m/sec
    
  }
  #speed <- speed_calc(df)
  speed <- c(speed,speed[length(speed)]*NA)
  df_ny <- cbind(df_her,speed)
  
  return(df_ny)
}
```


# define break finder with 'two-windows whole-length' fits
```{r}
# Define break finder function
breakfinder2 <- function(x, y, buffer) {
  # INPUTS: x, y - the series
  #         buffer - how long (in points) the two adjacent windows are
  
  # Validate inputs
  if (length(x) != length(y)) stop("x and y must be of the same length")
  if (buffer <= 0 || buffer >= length(y)) stop("Invalid buffer")
  
  # Initialize the results list
  listen <- data.frame(
    x = x,
    rmse = rep(NA, length(y))
  )
  
  for (ipos in (buffer + 1):(length(y) - buffer - 1)) {
    idx <- which( x <= x[ipos]) # from start to ipos-1
    jdx <- which( x > x[ipos] ) # from ipos to end
    
    # Fit both segments
    rlm_fit1 <- lm(y[idx] ~ x[idx])
    rlm_fit2 <- lm(y[jdx] ~ x[jdx])
    
    # Calculate the mean squared error (MSE)
    mse1 <- mean((y[idx] - rlm_fit1$fitted.values)^2)
    mse2 <- mean((y[jdx] - rlm_fit2$fitted.values)^2)
    mse <- mse1 + mse2
    rmse <- sqrt(mse)
    
    # Store the result
    listen$rmse[ipos] <- rmse
  }
  
  return(listen)
}
```

# define break finder with sliding windows
```{r}
# Define break finder function
breakfinder <- function(x, y, width) {
  # INPUTS: x, y - the series
  #         width - how long (in points) the two adjacent windows are
  
  # Validate inputs
  if (length(x) != length(y)) stop("x and y must be of the same length")
  if (width <= 0 || width >= length(y)) stop("Invalid width")
  
  # Initialize the results list
  listen <- data.frame(
    x = x,
    rmse = rep(NA, length(y))
  )
  
  for (ipos in (width + 1):(length(y) - width - 1)) {
    idx <- which(x > x[ipos - width] & x <= x[ipos])
    jdx <- which(x > x[ipos] & x <= x[ipos + width])
    
    # Fit both segments
    rlm_fit1 <- lm(y[idx] ~ x[idx])
    rlm_fit2 <- lm(y[jdx] ~ x[jdx])
    
    # Calculate the mean squared error (MSE)
    mse1 <- mean((y[idx] - rlm_fit1$fitted.values)^2)
    mse2 <- mean((y[jdx] - rlm_fit2$fitted.values)^2)
    mse <- mse1 + mse2
    rmse <- sqrt(mse)
    
    # Store the result
    listen$rmse[ipos] <- rmse
  }
  
  return(listen)
}
```


# loop
```{r}

for (ifil in 1:length(files))
{
  filename <- files[ifil]
  print(filename)
  descriptor <- strsplit(strsplit(filename,'/')[[1]][2],'.rds')[[1]][1]
  df <- readRDS(filename)
  df$DateTimeUTC <- as.POSIXct(df$DateTimeUTC)
  idx <- order(df$DateTimeUTC)
  df <- df[idx,]
  df <- speed_calc(df)
  idx <- which(df$speed != 0)
  df <- df[idx,]
  #
  par(mfrow=c(1,1))
  # Initialize the EM model with a guess of some clusters
  em_obj <- init.EM(df[,c(3,2)], nclass = 5, method = "em.EM")
  # Run the EM algorithm
  tmm_model <- emcluster(df[,c(3,2)],em_obj, assign.class=TRUE)
  
  # Assign each data point to a cluster
  cluster_assignments <- tmm_model$class
  
  # Model summary
  summary(tmm_model)
  
  #
  df$class <- cluster_assignments
  # Determine date range of each class
  dateRange <- data.frame(Class = integer(), StartDate = as.POSIXct(character()), EndDate = as.POSIXct(character()), stringsAsFactors = FALSE)
  for (iclust in unique(df$class)) {
    range_dates <- range(df$DateTimeUTC[df$class == iclust])
    dateRange <- rbind(dateRange, data.frame(Class = iclust, StartDate = range_dates[1], EndDate = range_dates[2], N = length(which(df$class == iclust))))
    
  }
  # Explicitly set timezone to UTC
  dateRange$StartDate <- as.POSIXct(dateRange$StartDate, origin="1970-01-01", tz = "UTC")
  dateRange$EndDate <- as.POSIXct(dateRange$EndDate, origin="1970-01-01", tz = "UTC")
  
  print(dateRange)
  # Plot Latitude vs Longitude
  par(mfrow=c(1,1))
  # Plot Latitude with colored segments
  plot(df$Longitude, df$Latitude, type="n", main=filename, xlab="Longitude", ylab="Latitude",pch=19,cex=0.3)
  for (i in unique(df$class)) {
    points(df$Longitude[df$class == i], df$Latitude[df$class == i], type="p", col=i,pch=19,cex=0.3)
  }
  # Plot Latitude
 # par(mfrow=c(2,1))
  # Plot Latitude with colored segments
  plot(df$DateTimeUTC, df$Latitude, type="n", main=filename, xlab="DateTimeUTC", ylab="Latitude",pch=19,cex=0.3)
  for (i in unique(df$class)) {
    points(df$DateTimeUTC[df$class == i], df$Latitude[df$class == i], type="p", col=i,pch=19,cex=0.3)
  }
  # Plot Longitude
 # par(mfrow=c(2,1))
  # Plot Longitude with colored segments
  plot(df$DateTimeUTC, df$Longitude, type="n", main=filename, xlab="DateTimeUTC", ylab="Longitude",pch=19,cex=0.3)
  for (i in unique(df$class)) {
    points(df$DateTimeUTC[df$class == i], df$Longitude[df$class == i], type="p", col=i,pch=19,cex=0.3)
  }
  # Plot speed
 # par(mfrow=c(2,1))
  # Plot speed with colored segments
  plot(df$DateTimeUTC, df$speed, type="n", main=filename, xlab="DateTimeUTC", ylab="speed",pch=19,cex=0.3, log='y')
  for (i in unique(df$class)) {
    points(df$DateTimeUTC[df$class == i], df$speed[df$class == i], type="p", col=i,pch=19,cex=0.3)
  }
  breaks <- as.data.frame(breakfinder2(df$DateTimeUTC,df$Longitude,24))
 # par(mfrow=c(2,1))
  plot(breaks,type="l",main="Two-segment analysis. Derivative is red")
  x <- breaks[,1]
  y <- breaks[,2]
  #lines(x[-length(x)], diff(y) / as.numeric(diff(x)), type="l",col=2)
  #plot(x, diff(y) / as.numeric(diff(x)), type="l")
  # Add the second graph
  par(new=TRUE)  # Allow new plot on top
  plot(x[-length(x)], diff(y) / as.numeric(diff(x)), type="l", col="red", axes=FALSE, xlab="", ylab="")
  
  # Add the second y-axis
  axis(side=4)  # Side 4 is the right side
  #
  saveRDS(dateRange,paste0('OUTPUT/dateRange_',descriptor,'.rds'))
} # end of ifil loop
```


