---
title: "Simple infrasound plotter"
output: 
  pdf_document: 
    fig_height: 8
---

Make simple signal plots 

```{r}
rm(list=ls())
setwd("~/WORKSHOP/QAANAAQ/")
datapath <- "/dmidata/projects/nckf/earthshine/Infrasound/I22FR/"
#datapath <- "/dmidata/projects/nckf/earthshine/Infrasound/I24FR/"
#datapath <- "/dmidata/projects/nckf/earthshine/Infrasound/I36FR/"
Sys.setenv(TZ="UTC")
#
#files <- list.files(path=datapath,pattern="37H\\d_BDF_.*\\.txt",full.names = T)
# List all files matching the pattern
files <- list.files(path=datapath, pattern="_BDF_", full.names=TRUE)

for (infilename in files)
{
  df <- read.csv(infilename,sep="",header=F)
  colnames(df) <- c("unixtime","signal")
  # Convert Unix time to POSIXct
  df$posix_time <- as.POSIXct(df$unixtime, origin="1970-01-01", tz="UTC")
  # plot
  plot(df$posix_time,df$signal,pch=19,cex=0.1,xlab="Date",ylab='Sensor signal',main=infilename)
  print(c(nrow(df),infilename))
}
```
# plot detaljer
```{r}
for (infilename in files)
{
  df <- read.csv(infilename,sep="",header=F)
  colnames(df) <- c("unixtime","signal")
  # Convert Unix time to POSIXct
  df$posix_time <- as.POSIXct(df$unixtime, origin="1970-01-01", tz="UTC")
  # plot
  plot(df$posix_time,df$signal,pch=19,cex=0.1,xlab="Date",ylab='Sensor signal',main=infilename, 
       xlim=c(as.POSIXct("2022-01-15 05:30:00 UTC"), as.POSIXct("2022-01-15 06:00:00 UTC")))
  print(c(nrow(df),infilename))
}
```


