---
title: "Series breaks, with strucchange"
output: 
  pdf_document: 
    fig_height: 7
---

```{r}
rm(list=ls())
setwd("~/WORKSHOP/QAANAAQ/")
# Load the strucchange package
library(strucchange)
library(readxl)
library(openxlsx)
library(lubridate)
library(circular)
#
df <- as.data.frame(read_excel('DATA/Windspeed.xlsx'))
df$hour <- hour(df$Date)
df$month <- month(df$Date)
df$year <- year(df$Date)
df <- df[,-5]
df <- df[,-5]
df[,2] <- as.numeric(df[,2])
df[,3] <- as.numeric(df[,3])
df[,4] <- as.numeric(df[,4])

```


```{r}
x <- seq(from=1,to=nrow(df))
y <- df$Farquhar2022

# Plot the time series
plot(x, y, type = "l", main = "Time Series Data")

# Detect breakpoints using the strucchange package
breakpoints <- breakpoints(y ~ x)

# Plot the breakpoints
plot(breakpoints)

# Summary of the breakpoints
summary(breakpoints)

```
 
 #
```{r}
## fit null hypothesis model and model with 1 breakpoint
fm0 <- lm(y ~ 1)
fm1 <- lm(y ~ breakfactor(breakpoints, breaks = 1))
fm2 <- lm(y ~ breakfactor(breakpoints, breaks = 2))
plot(y)
lines(ts(fitted(fm0), start = 1), col = 'red', lwd=3)
lines(ts(fitted(fm1), start = 1), col = 3, lwd=3)
lines(ts(fitted(fm2), start = 1), col = 4, lwd=3)
lines(breakpoints)
```
 
 #
```{r}
#---
# Detect breakpoints using the breakpoints() function
bp <- breakpoints(y ~ x)

# Get the breakpoints
breakpoints <- breakpoints(bp)$breakpoints

# Plot the time series with breakpoints
plot(x, y, type = "l", main = "Time Series Data with Breakpoints")
abline(v = breakpoints, col = "red",lwd=3)
lines(x,y)

# Add labels for the breakpoints
for (i in 1:length(breakpoints)) {
  text(breakpoints[i], y[breakpoints[i]]+15, labels = paste("Bp.", i), pos = 3)
}
```
 
 