---
title: "Trilateration"
output: 
  pdf_document: 
    fig_height: 7
    fig_caption: yes
---

Trilateration for the Qaanaaq data. L-BFGS-B is able to solve the x,y location of the source.

CNEOS data here: https://cneos.jpl.nasa.gov/fireballs/

2018-07-25 21:55:26	76.9N	69.0W is the event as seen from space

```{r}
rm(list=ls())
setwd("~/WORKSHOP/QAANAAQ/")
library(nleqslv)
library(sp)
library(lubridate)
library(oce)
library(nloptr)
library(maps)
library(ggplot2)
library(ggmap)
library(parallel)
library(sf)
library(e1071)
library(astrochron)
library(MCMCpack)
# constants
# speed of sound
c = 343 # m/s
c <- c/1000  # km/s
#
df <- read.csv("DATA/offsets.txt",header=TRUE,sep=",")
coords <- read.csv("DATA/coordinates.txt",header=TRUE,sep=",")
#
# Merge the data frames by the "ID" column
merged_df <- merge(df, coords, by = "Station", all = TRUE)
df <- merged_df
#
plot(coords$Longitude,coords$Latitude,pch=4)
text(coords$Longitude,coords$Latitude,coords$Station)
```



```{r}

#
# Create a SpatialPoints object
points <- SpatialPoints(cbind(df$Longitude, df$Latitude), proj4string = CRS("+proj=longlat +ellps=WGS84"))

# Define the target projection
target_projection <- "+proj=utm +zone=19 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"

# Transform the coordinates to the target projection
transformed_points <- spTransform(points, CRS(target_projection))

# Extract the easting and northing
df$easting <- transformed_points@coords[,1]/1000
df$northing <- transformed_points@coords[,2]/1000

plot(df$easting ,df$northing ,asp=1,xlab="Easting [km]",ylab="Northing [km]",pch=19,cex=0.5)


# also calculate easting and northing of known BANG position
source <- SpatialPoints(cbind(-69.0,76.9),proj4string = CRS("+proj=longlat +ellps=WGS84"))
# Transform the coordinates to the target projection
transformed_points_source <- spTransform(source, CRS(target_projection))
source_easting <- transformed_points_source@coords[,1] # in meters
source_northing <- transformed_points_source@coords[,2]
```


#----------------------------- MCMC ----------------------------------------
#
```{r}
# Define prior distributions for parameters
prior_function <- function(parameters) {
  # Define prior distributions for each parameter
  # use km for eastings and northings
  min_easting <- 0
  max_easting <- 1000
  min_northing <- 7000
  max_northing <- 9000
  min_height <- 0
  max_height <- 100
  min_t0 <- -500
  max_t0 <- 0
  if (parameters[1] < min_easting || parameters[1] > max_easting ||
      parameters[2] < min_northing ||
      parameters[2] > max_northing ||
      parameters[3] < min_height || parameters[3] > max_height ||
      parameters[4] < min_t0 || parameters[4] > max_t0) {
    return(-300)  # Return negative number
  }
  # Otherwise, return 0 - assuming the prior gives log(p)
  return(0)
}
```
#
```{r}
calculate_predicted_times <-
  function(easting, northing, height, t0, y, X, c) {
    # Initialize a vector to store the predicted times
    predicted_times <- numeric(8)
    # Calculate predicted times for each station
    for (i in 1:8) {predicted_times[i] <- t0 + sqrt((X$V2[i] - easting) ^ 2 + (X$V3[i] - northing) ^ 2 + (0 - height) ^2) / c }
    
    return(predicted_times)
  }

```



```{r}
# Define log merit function
log_merit_function <- function(parameters, y, X) {
  print(c('params : ',c(round(parameters,2))))
  # Calculate error function
  # Extract parameters
  easting <- parameters[1]
  northing <- parameters[2]
  height <- parameters[3]
  t0 <- parameters[4]
  # Calculate predicted arrival times
  predicted_times <- calculate_predicted_times(easting, northing, height, t0, y, X, c)
  # Calculate errors
  errors <- y - predicted_times
  # Calculate negative log-likelihood (sum of squared errors)
  sigma <- c(0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05)*1.1 # Assuming constant variance
  negative_log_likelihood <- -0.5 * sum((errors / sigma)^2) # + log(2 * pi * sigma^2))
  # Calculate prior function
  neg_log_prior <- prior_function(parameters) # this should return -log(prior)
  # Calculate log likelihood (assuming normal errors)
  #log_likelihood <- negative_log_likelihood  
  # Calculate log posterior (log likelihood + log prior)
  log_posterior <- negative_log_likelihood + neg_log_prior
  return(log_posterior)
}
```
 "522.619268298149"       "8531.09977427125" 
                      x3                       x4 
       "39.502155482769"      "-245.345844954252" 

# MCMC
```{r}

# Set up MCMC sampler
n_iter <- 100000  # Number of iterations
n_burn <- 2000  # Number of burn-in iterations
initial_guess <- c(xx = 515, yy = 8545, zz = 61, t0 = -245)  # Initial guess with RMSE=0.34 s
initial_guess <- c(xx = 535, yy = 8506, zz = 90, t0 = -397)  # Initial guess with RMSE=0.31 s
initial_guess <- c(xx = 537, yy = 8497, zz = 60, t0 = -350) 
initial_guess <- c(xx = 522, yy = 8531, zz = 39.5, t0 = -245.3)
#initial_guess <- c(xx = 731, yy = 8053., zz = 321, t0 = 1200)  # Initial guess
# Set up MCMC sampler
# Call MCMC sampling function
y <- as.data.frame(df$t_offset)
X <- as.data.frame(cbind(1, df$easting, df$northing))
post.samp <- MCMCmetrop1R(log_merit_function, y = y, X = X, mcmc = n_iter + n_burn, thin = 10, tune=.1, theta.init = initial_guess) 

summary(post.samp)

for (ichain in 1:ncol(post.samp))
{
  plot(post.samp[,ichain])
  abline(h=0,col=2)
}
 

# Calculate the residuals in observing times
 
med_easting <- median(post.samp[,1])
med_northing <- median(post.samp[,2])
med_height <- median(post.samp[,3])
med_t0 <- median(post.samp[,4])
print(c('Median chain values : ',med_easting,med_northing,med_height,med_t0))
pred_times <- calculate_predicted_times(med_easting,med_northing,med_height,med_t0,y,X,c)
print(c('Predicted times from median parameter values: ',pred_times))
residuals <- df$t_offset - pred_times
print(c('Residuals: ',residuals,' s. RMSE = ',sqrt(sum(residuals^2)),' s.'))
```




