---
title: "Statistical analysis of wind directions at glaciers & melange"
output: 
  pdf_document: 
    fig_height: 7
---

 
```{r}
rm(list=ls())
setwd("~/WORKSHOP/QAANAAQ/")
library(readxl)
library(openxlsx)
library(lubridate)
library(circular)
#
df <- as.data.frame(read_excel('DATA/Winddirection.xlsx'))
df$hour <- hour(df$Date)
df$month <- month(df$Date)
df$year <- year(df$Date)
df <- df[,-5]
df <- df[,-5]
df[,2] <- as.numeric(df[,2])/180*pi # convert angles to radians
df[,3] <- as.numeric(df[,3])/180*pi
df[,4] <- as.numeric(df[,4])/180*pi
# transform 0 to 2pi to -p1 to pi
idx <- which(df[,2] > pi)
df[,2] <- pi - df[,2]
idx <- which(df[,3] > pi)
df[,3] <- pi - df[,3]
idx <- which(df[,4] > pi)
df[,4] <- pi - df[,4]



colnames(df)
#
p_lim <- 0.05
```


# Test if wind-direction distributions at each station are drawn from the same population
```{r}
par(mfrow=c(3,2))
linjen <- NULL
for (imo in unique(df$month))
{
  for (ihour in unique(df$hour)){
    idx <- which (df$hour == ihour & df$month == imo)
  dist_Far <- df$Farquhar2022[idx]
  dist_Mel <- df$Melville2022[idx]
  dist_Tra <- df$Tracy2022[idx]
  #
  tstr <- paste("Wind directions for hour, month = ",ihour,imo)
#  plot(hist(dist_Far),col=2,main=tstr,xlab="Speed [m/s]",ylab="hist",xlim=c(-pi,pi))
#  lines(hist(dist_Mel),col=3)
#  lines(hist(dist_Tra),col=4)     
  t12 <- ks.test(dist_Far,dist_Mel)
  t13 <- ks.test(dist_Far,dist_Tra)
  t23 <- ks.test(dist_Mel,dist_Tra)
  linjen <- rbind.data.frame(linjen,c(ihour,imo,t12$p.value,t13$p.value,t23$p.value))
  }
}
colnames(linjen) <- c("Hour","Month","p_Far_Mel","p_Far_Tra","p_Mel_Tra")
```

# Are the p values consistent with 'directions are drawn from same pop?'
```{r}
# testing pairs of distributions at a given critical p value
p_lim <- 0.05
idx <- which(linjen$p_Far_Mel > p_lim)
print(paste("There are ",length(idx)," situations where Farquar and Melville directions could be drawn from same distribution. p_crit = ",p_lim))
print(linjen[idx,c(1,2)])
#
idx <- which(linjen$p_Far_Tra > p_lim)
print(paste("There are ",length(idx)," situations where Farquar and Tracy directions could be drawn from same distribution. p_crit = ",p_lim))
print(linjen[idx,c(1,2)])
#
idx <- which(linjen$p_Mel_Tra > p_lim)
print(paste("There are ",length(idx)," situations where Melville and Tracy directions could be drawn from same distribution. p_crit = ",p_lim))
print(linjen[idx,c(1,2)])
```


# look at whether directions differ by time of day
```{r}
png("FIGURES/wind_direction.png")
par(mfrow = c(2, 2))
linjen <- NULL

for (ihour in unique(df$hour)) {
  idx <- which (df$hour == ihour)
  dist_Far <- df$Farquhar2022[idx]
  dist_Mel <- df$Melville2022[idx]
  dist_Tra <- df$Tracy2022[idx]
  #
  plot(density(dist_Far),col=2,main=paste('Hour = ',ihour),lwd=3,xlab="Wind direction [radians]",ylim=c(0,1.2))
  lines(density(dist_Mel),col=3,lwd=3)
  lines(density(dist_Tra),col=4,lwd=3)
  #
  tstr <- paste("Wind directions for hour = ", ihour)
  
  t12 <- ks.test(dist_Far, dist_Mel)
  t13 <- ks.test(dist_Far, dist_Tra)
  t23 <- ks.test(dist_Mel, dist_Tra)
  linjen <-
    rbind.data.frame(linjen, c(ihour,  t12$p.value, t13$p.value, t23$p.value))
}
dev.off()
colnames(linjen) <-
  c("Hour",  "p_Far_Mel", "p_Far_Tra", "p_Mel_Tra")
#
linjen
```

 